services:
  web:
    build: .
    container_name: shortener_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - POSTGRES_DB=shorty
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: shortener_db
    restart: always
    environment:
      - POSTGRES_DB=shorty
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shorty"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
