name: Simple CI

on:
  push:
    branches: [ main ]

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Run containers
        run: |
             docker compose up --build -d
             docker ps
             sleep 10
             docker logs shortener_app

      -  name: Create deployment package
         run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to elastic beanstalks
        uses: einaregilsson/beanstalk-deploy@v20
        with:
         aws_access_key: ${{secrets.aws_Access_Key}}
         aws_secret_key: ${{secrets.aws_Secret_Key}}
         application_name: 'testo'
         environment_name : "testo-env"
         region: "eu-north-1"
         version_label: ${{github.sha}}
         deployment_package: deploy.zip
         use_existing_version_if_available: true

